### ISSUE TITLE
App audit - This issue is for documentation purposes (WIP)

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/dwellingly-app#366]
- [ ] Verify correct auth is in place for all resources. Need @htharker42 input

- Lease - Roles allowed (  )
- Tenant - Roles allowed ( currently only admin access )
- Property - Roles allowed (  )
- User - Roles allowed (  )

**Authorizations**
- [x] What is the difference between JOIN staff and Property Managers? Page 18
        - JOIN staff has tenants. PM's can belong to many properties. Do PM's have access to tenants? No. (Probably can only see the names of tenants) -> Ask Hugh to clarify.
- [x] Admins cannot delete themselves. Page 18 Issue created #496 
- [x] Admins can create new admins/JOIN staff Page 19
- [x] resources/user.py why is archiving a user a separate route? What is an archived user? 

**Emergency Contacts** Page 22 and 23
- [x] ContactNumberModel - column Number cannot be Null
- [x] EmergencyContactModel 
  - [x]  contact Numbers cannot be empty. Must have at least one association issue #497
  - [x] Name cannot be Null

** Forgot Password**
- [x] Currently being implemented

**ASK HUGH**
- [x] should name be unique? If we have a method to find_by_name it suggests name should be unique.

**Lease** ???
 - [x] Lease has a foreinKey to a landlordID - How is this different from property manager? I'm removing this. Tenants do not have landlords. They can be housed, which the property they're housed at can have property managers. FE and BE is not using landlordID anywhere. As far as I can see it is safe to remove.
 - [x] There doesn't seem to be a UI spec for performing CRUD actions on a lease. - I only see a lease duration input on the add tenant screen. Lease resource is scheduled to be removed. issue #449  - Needs Discussion!!!
 - [x] Lease has `dateTimeStart` and `dateTimeEnd` perhaps instead of datetime objects they're simply date objects. `startDate` and `endDate`. Hugh said to keep the time as a lease may have an end time.

**Tenants**
- [x] Why is there a tenant role? Are they users of the app? It seems we should remove tenant role. Page 6 and 7 Remove tenant. and Fix https://github.com/codeforpdx/dwellinglybackend/pull/110/files#diff-1f750d3116b7157d0f24266b235b5522R215 issue #432 and #433
- [x] Add reverse relationship for tenant/staff many to many association. (Need to create issue)
- [x] What are unhoused tenants? Page 8 - Perhaps when tenant is created default to unhoused. tenants are not required to be assigned a property. If a tenant does not have a lease then they can be considered unhoused. Tenants should have a 1:1 relationship with a lease
- [x] Tenant should have a 1 to 1 relationship with a lease. (Need to create issue eventually, later sometime)
- [x] Can tenants be removed from the database? Page 58 - Archive Tenants. BE issue #450 FE issue #451
- [x] Verify valid payload for creating a tenant. Page 11
       - Tenant is not required to be assigned to property???. Page 13 This is correct. Tenant does not need to be assigned and this means they're unhoused.

- [ ] Tenants - FE needs to be updated to search for tenants by property AND/OR join staff Page 29 - FRONTEND
- [x] Do tenants need to be assigned at least one Join Staff? Probably. Lets say no for now. 
- [x] FE - Tenants Add New button needs implemented.
- [x] Page 48 seems off-putting. Tenant cannot be saved without being assigned a property, and it seems they can be assigned multiple properties…. ignore this page for now. Delete page 48 from memory.
      - Page 62 shows that tenants can be saved without property.

**Tickets**
- [x] Missing relationship for tenant and tickets. A tenant has many tickets. Page 9 - Issue #498
- [x] A user can be assigned tickets. What kind of user? Join Staff . Issue #499
- [x] A user can send (create?) tickets. What kind of user? any user
- [x] A ticket can be new, in progress, or closed. Currently status is a string. `status = db.Column(db.String(12))` Possibly change this to an ENUM. On page 9 & 10 status represents open or closed though?, and Page 21 represents new, in progress, closed.  Change this.
            - So I'm assuming open means it is either new or in progress. Perhaps this logic is handled in the frontend and we can represent a ticket as new, in progress, or closed in the backend. ???? If not maybe we should create an active (boolean) attribute to represent open/closed?
           - is it possible tickets can be created, but get closed without ever being in progress. tickets must be assigned which goes to in progress. Wether they're acted on or not doesn't matter to us.
Ticket is created, and has new status, when assigned it goes to in progress, when closed its closed. #404 

- [ ] Need to implement pagination for tickets. Page 20 - FRONTEND
- [ ] Need to implement filters for tickets. Page 21 issue #425 FRONTEND
       - Filter by date range (opened from), category, status.
       - hmmm. tickets currently don't have a category. Do we need category model? YES. Need to get more info on. FE has two Categories labeled complaints and maintenance, yet the designs indicate there should be more specific categories

- [ ] Tickets can be sorted by `created_at` or `updated_at` - Currently FE implements sorting on all columns. FRONTEND
- [ ] FE needs to be updated to display tickets according to design. Page 20. Details missing in columns FRONTEND

- [ ] Need Create and update interface. No UI docs for this. (Page 9) FRONTEND
- [ ] Perhaps add a plus sign next to ticket label on Page 9 and maybe one on index page. FRONTEND
- [ ] Constraints for creating a ticket? Tenant must be assigned property? Needs Discussion.
- [ ] Perhaps able to update ticket when viewing ticket show window (Page 31) FRONTEND
- [x] Remove unused `minPastUpdate` column. It's already a virtual field and the db column is not used. #416 

**Notes**
- [ ] Note might need to be its own resource. Currently a note is created through the update action on a ticket. If we every need to Edit, Update, or Delete notes then we should seriously consider moving the Notes CRUD stuff to its own Resource instead of doing it all through the tickets resource. 

**Property**
- [x] Verify and Fix relationship between Property and PropertyManager. Can there be more than one PM? Yes. Page 50 Many to Many relationship. Issue #370
- [x] A property manager (user) can be the manager of many properties. Page 17 YES PR codeforpdx/dwellinglybackend/pull/131

- [x] Issue #314 Adding Property Manager assignment to property (FRONTEND)

- [x] Add db constraints. Required fields cannot be Null - Issue #500
Name
Address
City
STate
Zip
 
**Join Staff**
 - [x] ~~Should be able to terminate a staff member without first reassigning all their tenants? Probably Not. Association to have at least one Join Staff should prevent this. Let's make sure Join staff can't be deleted until all tenants are re-assigned.~~
 Will probably have to come back to this 👆 Bulk updates was implemented per frontend request and it removes all associations then reassigns........

**Roles**
- [x] Remove tenant role issue #432 
- [x] A user is either authorized to access the site or not. Anyone without a role assigned is not allowed access. Update User Login to check that a user must have a role in order to be logged in. Issue #501 
- [x] Create/update endpoint to return "pending" users (A pending user is one without a role and who is not archived) instead of users with the role Pending. Issue #502 
- [x] Remove pending role Issue #504 
- [x] Update the FE to remove the pending role Issue #503 

- [x] An admin is everything a staff role is, but with admin privs. Page 7

@Chris-Boe and @htharker42 

Related to codeforpdx/dwellingly-app/357
